package gui;

import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;
import modules.IOFile;
import modules.XuLy;
import modules.Vigenere;
import tcp.Server;

/**
 *
 * @author Nhom1
 */
public class MainServerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainServerFrame
     */
    private static Server runServer;
    private static String key = "abc";

    public MainServerFrame() {

        initComponents();
        this.setLocationRelativeTo(null);
        txtKey.setText(key);

        try {
            runServer = new Server();

            new Thread(new Runnable() {
                @Override
                public void run() {

                    try {

                        while (true) {
                            Socket client = runServer.getServer().accept();
                            runServer.acceptClient(client);

                            String sig = runServer.revData();
                            switch (sig) {
                                case "test":
                                    runServer.sendData("success");
                                    break;
                                case "content":
                                    String input = runServer.revData();
                                    String fileName = runServer.revData();
                                    String filePath = "src/files/" + fileName;
//                                    if(IOFile.isFileExist(filePath)){
//                                        runServer.sendData("fileexist");
//                                        break;
//                                    }
                                    if (rb_KyTu.isSelected()) {
                                        IOFile.saveFileCharacterStream(filePath, Vigenere.encrypt(input, key));
                                        System.out.println("CSTREAM");
                                    } else {
                                        IOFile.saveFileByteStream(filePath, Vigenere.encrypt(input, key));
                                        System.out.println("BSTREAM");
                                    }
                                    runServer.sendData("createdfile");
                                    if (rb_KyTu.isSelected()) {
                                        runServer.sendData(IOFile.convertFromList(XuLy.timTuXuatHienNhieuNhat(IOFile.convertFromString(Vigenere.decrypt(IOFile.readFileCharacterStream(filePath), key)))));
                                    } else {
                                        runServer.sendData(IOFile.convertFromList(XuLy.timTuXuatHienNhieuNhat(IOFile.convertFromString(Vigenere.decrypt(IOFile.readFileByteStream(filePath), key)))));
                                    }

                                    break;
                            }

                            client.close();
                        }
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }

                }
            }).start();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Server đã khởi động!");
            System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        btnUpdateKey = new javax.swing.JButton();
        rb_KyTu = new javax.swing.JRadioButton();
        rb_NhiPhan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVER");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Xử Lý");

        jLabel2.setText("Key");

        btnUpdateKey.setText("Cập nhật");
        btnUpdateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKeyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_KyTu);
        rb_KyTu.setSelected(true);
        rb_KyTu.setText("Ký tự");

        buttonGroup1.add(rb_NhiPhan);
        rb_NhiPhan.setText("Nhị phân");

        jLabel3.setText("Dạng đọc ghi file:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_KyTu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_NhiPhan))
                    .addComponent(txtKey, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateKey)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateKey))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb_KyTu)
                    .addComponent(rb_NhiPhan))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKeyActionPerformed
        // TODO add your handling code here:
        if (!txtKey.getText().matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(null, "Định dạng key không đúng!");
            return;
        }
        txtKey.setText(txtKey.getText().toLowerCase());
        key = txtKey.getText();
        JOptionPane.showMessageDialog(null, "Đã cập nhật key!");
    }//GEN-LAST:event_btnUpdateKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainServerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateKey;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_KyTu;
    private javax.swing.JRadioButton rb_NhiPhan;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables
}
